### ISSUE TITLE
cygwin tests run suspiciously few tests

### ISSUE THREAD

**Issue by judovana** [rh-openjdk/ssl-tests#23]
My only suspicion goes to https://github.com/rh-openjdk/ssl-tests/blob/master/jtreg-wrappers/SysDepsProps.java which is most likely cygwin-unfriendly

**Comment by zzambers** [comment]
I think this is probably because I currently only run external clients on linux, e.g.:
https://github.com/rh-openjdk/ssl-tests/blob/b81d0e3537fe876b219c262db110799df95d629f/jtreg-wrappers/ssl-tests-gnutls-client.sh#L3

**Comment by judovana** [comment]
So the 
```
XML output  to D:\a\ssl-tests\ssl-tests\test.1709911879\jdk\JTwork
Passed: ssl-tests.sh
Passed: ssl-tests-bc-2nd.sh
Passed: ssl-tests-bcfips.sh
Passed: ssl-tests-bcjsse.sh
Test results: passed: 4
```

Are all what is expected from you?

**Comment by zzambers** [comment]
Yy, that is what is currently expected on windows.

**Comment by judovana** [comment]
On jdk21 it i sjust:
```
Passed: ssl-tests.sh
Passed: ssl-tests-bc-2nd.sh
Passed: ssl-tests-bcjsse.sh
Test results: passed: 3
```

Still ok?

I guess so.. pls close the issue if so. TY!

**Comment by zzambers** [comment]
yy
